export interface TpsSeedItem {
  nama: string;
  kecamatan: string;
  latitude: number;
  longitude: number;
  bangunan: string | null;
  mobilitas: string | null;
  jumlah_bak: number | null;
  jenis: string | null;
}

export const TPS_SEED_DATA: TpsSeedItem[] = [
  { nama: 'TPS Gotong Royong', kecamatan: 'Palaran', latitude: -0.546758, longitude: 117.158, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: 1, jenis: 'BETON' },
  { nama: 'TPS Segara', kecamatan: 'Palaran', latitude: -0.55325, longitude: 117.162175, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pasar Palaran', kecamatan: 'Palaran', latitude: -0.562347, longitude: 117.180839, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Handil Bhakti', kecamatan: 'Palaran', latitude: -0.589603, longitude: 117.174503, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Peti Kemas', kecamatan: 'Palaran', latitude: -0.580308, longitude: 117.206183, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Bantias', kecamatan: 'Palaran', latitude: -0.630875, longitude: 117.202742, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Stadion Palaran', kecamatan: 'Palaran', latitude: -0.584536, longitude: 117.135472, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Handil Bhakti', kecamatan: 'Palaran', latitude: -0.589069, longitude: 117.174669, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Simpang Pasir', kecamatan: 'Palaran', latitude: -0.580806, longitude: 117.130869, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPS Daeng Mangkonang', kecamatan: 'Samarinda Seberang', latitude: -0.517964, longitude: 117.150383, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Baqa', kecamatan: 'Samarinda Seberang', latitude: -0.512939, longitude: 117.140919, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pasar Komura', kecamatan: 'Samarinda Seberang', latitude: -0.525639, longitude: 117.150331, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Bung Tomo', kecamatan: 'Samarinda Seberang', latitude: -0.519458, longitude: 117.121747, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Baqa', kecamatan: 'Samarinda Seberang', latitude: -0.512867, longitude: 117.140978, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPS Harapan Baru', kecamatan: 'Loa Janan Ilir', latitude: -0.539492, longitude: 117.110075, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Bawah Jembatan Mahulu', kecamatan: 'Loa Janan Ilir', latitude: -0.556536, longitude: 117.086492, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS H. Saleh', kecamatan: 'Loa Janan Ilir', latitude: -0.576536, longitude: 117.098311, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Tani Aman', kecamatan: 'Loa Janan Ilir', latitude: -0.586319, longitude: 117.109481, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Sma N 4', kecamatan: 'Loa Janan Ilir', latitude: -0.518319, longitude: 117.141383, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Labaika', kecamatan: 'Loa Janan Ilir', latitude: -0.516228, longitude: 117.143175, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Tani Aman', kecamatan: 'Loa Janan Ilir', latitude: -0.5865, longitude: 117.109586, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPS Go. Subur', kecamatan: 'Sungai Kunjang', latitude: -0.524825, longitude: 117.104753, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Jl. Ekonomi', kecamatan: 'Sungai Kunjang', latitude: -0.559975, longitude: 117.078058, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Perum Pemda', kecamatan: 'Sungai Kunjang', latitude: -0.492056, longitude: 117.119672, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pasar Kedondong', kecamatan: 'Sungai Kunjang', latitude: -0.508333, longitude: 117.116819, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Adam Malik', kecamatan: 'Sungai Kunjang', latitude: -0.515172, longitude: 117.115317, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPST To Loa Bakung', kecamatan: 'Sungai Kunjang', latitude: -0.529322, longitude: 117.090467, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Perum Daksa', kecamatan: 'Sungai Kunjang', latitude: -0.506489, longitude: 117.084497, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Ir Sutam', kecamatan: 'Sungai Kunjang', latitude: -0.520931, longitude: 117.111964, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Ring Road', kecamatan: 'Sungai Kunjang', latitude: -0.482947, longitude: 117.097272, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Ring Road', kecamatan: 'Sungai Kunjang', latitude: -0.483189, longitude: 117.09735, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPS Polres', kecamatan: 'Sungai Kunjang', latitude: -0.516953, longitude: 117.114939, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Arjuna', kecamatan: 'Samarinda Ulu', latitude: -0.498994, longitude: 117.140056, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pasundan', kecamatan: 'Samarinda Ulu', latitude: -0.495797, longitude: 117.137247, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Gjekan', kecamatan: 'Samarinda Ulu', latitude: -0.492467, longitude: 117.141725, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Siradu Salman', kecamatan: 'Samarinda Ulu', latitude: -0.491536, longitude: 117.138269, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Batu Lumpang', kecamatan: 'Samarinda Ulu', latitude: -0.485306, longitude: 117.135503, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Anggur', kecamatan: 'Samarinda Ulu', latitude: -0.481547, longitude: 117.140928, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Juanda II', kecamatan: 'Samarinda Ulu', latitude: -0.482753, longitude: 117.131994, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Folder Air Hitam', kecamatan: 'Samarinda Ulu', latitude: -0.467494, longitude: 117.136467, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Ring Road 2', kecamatan: 'Samarinda Ulu', latitude: -0.467853, longitude: 117.122472, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Tanjakan Bukit Pinang', kecamatan: 'Samarinda Ulu', latitude: -0.461336, longitude: 117.114817, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pemancingan', kecamatan: 'Samarinda Ulu', latitude: -0.450294, longitude: 117.106992, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Graha Indah', kecamatan: 'Samarinda Ulu', latitude: -0.478153, longitude: 117.119544, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Rawa Sari', kecamatan: 'Samarinda Ulu', latitude: -0.485328, longitude: 117.124961, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Taman Cerdas', kecamatan: 'Samarinda Ulu', latitude: -0.475872, longitude: 117.150689, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Tri Sar', kecamatan: 'Samarinda Ulu', latitude: -0.479306, longitude: 117.146222, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Bukit Pinang', kecamatan: 'Samarinda Ulu', latitude: -0.457053, longitude: 117.114447, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Polder', kecamatan: 'Samarinda Ulu', latitude: -0.467331, longitude: 117.134825, bangunan: 'Tertutup', mobilitas: null, jumlah_bak: null, jenis: null },
  { nama: 'TPS Rujab Walikota', kecamatan: 'Samarinda Ulu', latitude: -0.475278, longitude: 117.149592, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Rujab Wawalikota', kecamatan: 'Samarinda Ulu', latitude: -0.464606, longitude: 117.149356, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Milono', kecamatan: 'Samarinda Kota', latitude: -0.497392, longitude: 117.143178, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Mulawarman', kecamatan: 'Samarinda Kota', latitude: -0.50575, longitude: 117.157261, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Harmonika', kecamatan: 'Samarinda Kota', latitude: -0.489244, longitude: 117.148239, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Gunung Tangga', kecamatan: 'Samarinda Utara', latitude: -0.452697, longitude: 117.19975, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Perum Korem', kecamatan: 'Samarinda Utara', latitude: -0.438586, longitude: 117.196633, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS SMP N 19', kecamatan: 'Samarinda Utara', latitude: -0.394347, longitude: 117.253158, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pampang', kecamatan: 'Samarinda Utara', latitude: -0.3795, longitude: 117.228494, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pasar Hewan', kecamatan: 'Samarinda Utara', latitude: -0.428667, longitude: 117.219825, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Kandang Sapi', kecamatan: 'Samarinda Utara', latitude: -0.451047, longitude: 117.143311, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS PM. Noor', kecamatan: 'Samarinda Utara', latitude: -0.450736, longitude: 117.155514, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Batu Cermin', kecamatan: 'Samarinda Utara', latitude: -0.435669, longitude: 117.1429, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Bayam', kecamatan: 'Samarinda Utara', latitude: -0.421994, longitude: 117.169789, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Padat Karya', kecamatan: 'Samarinda Utara', latitude: -0.432353, longitude: 117.156167, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pinang Seribu', kecamatan: 'Samarinda Utara', latitude: -0.41415, longitude: 117.162936, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Lempake', kecamatan: 'Samarinda Utara', latitude: -0.436936, longitude: 117.190342, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Lempake', kecamatan: 'Samarinda Utara', latitude: -0.436956, longitude: 117.190228, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPST Insinerator Wanyi', kecamatan: 'Samarinda Utara', latitude: -0.420775, longitude: 117.163342, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS3R Mugirejo', kecamatan: 'Samarinda Utara', latitude: -0.482797, longitude: 117.214467, bangunan: 'Tertutup', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Gg. Ayu', kecamatan: 'Sungai Pinang', latitude: -0.461878, longitude: 117.176664, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Gerilya', kecamatan: 'Sungai Pinang', latitude: -0.484636, longitude: 117.168272, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pelita', kecamatan: 'Sungai Pinang', latitude: -0.484164, longitude: 117.163833, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Eks. Bandara', kecamatan: 'Sungai Pinang', latitude: -0.480828, longitude: 117.156947, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Jelawat Gg. 10', kecamatan: 'Samarinda Ilir', latitude: -0.497414, longitude: 117.159714, bangunan: 'Tertutup', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Jelawat Gg. 1', kecamatan: 'Samarinda Ilir', latitude: -0.5025, longitude: 117.159336, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Lumba Lumba', kecamatan: 'Samarinda Ilir', latitude: -0.519622, longitude: 117.160725, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Sultan Alimudin', kecamatan: 'Samarinda Ilir', latitude: -0.524919, longitude: 117.156878, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Gunung Manggah', kecamatan: 'Samarinda Ilir', latitude: -0.507192, longitude: 117.165592, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Kapten Suedjono', kecamatan: 'Sambutan', latitude: -0.5197, longitude: 117.178072, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Perum Arisco', kecamatan: 'Sambutan', latitude: -0.517142, longitude: 117.175078, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pelita 4', kecamatan: 'Sambutan', latitude: -0.509567, longitude: 117.183119, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pelita 8', kecamatan: 'Sambutan', latitude: -0.524292, longitude: 117.212708, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Makroman', kecamatan: 'Sambutan', latitude: -0.528053, longitude: 117.220972, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Sindang Sari', kecamatan: 'Sambutan', latitude: -0.564175, longitude: 117.235497, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Bawah Mahkota II', kecamatan: 'Sambutan', latitude: -0.53005, longitude: 117.162381, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Pelita 7', kecamatan: 'Sambutan', latitude: -0.514836, longitude: 117.20595, bangunan: 'Terbuka', mobilitas: 'Dinamis', jumlah_bak: null, jenis: null },
  { nama: 'TPS Telkom', kecamatan: 'Sambutan', latitude: -0.520061, longitude: 117.202397, bangunan: 'Terbuka', mobilitas: 'Statis', jumlah_bak: null, jenis: null },
];